-- Create DataWarehouse
CREATE OR REPLACE WAREHOUSE CRYPTO_WH 
WITH 
    WAREHOUSE_SIZE = 'XSMALL' 
    AUTO_SUSPEND = 60 
    AUTO_RESUME = TRUE 
    COMMENT = 'Computing power for crypto pipeline';

-- Database
CREATE OR REPLACE DATABASE CRYPTO_DB;

-- Raw Schema
CREATE OR REPLACE SCHEMA CRYPTO_DB.RAW;

-- Staging Schema
CREATE OR REPLACE SCHEMA CRYPTO_DB.STAGING;

-- Marts Schema
CREATE OR REPLACE SCHEMA CRYPTO_DB.MARTS;

-- Change Schema
USE SCHEMA CRYPTO_DB.RAW;

-- Create TABLE
CREATE OR REPLACE TABLE CRYPTO_DB.RAW.COINGECKO_MARKET_DATA (
    RAW_DATA VARIANT,
    FILE_NAME VARCHAR,
    INGESTION_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);